# Generated by Django 5.2.12 on 2026-03-21 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Customer full name", max_length=200),
                ),
                (
                    "mobile",
                    models.CharField(
                        help_text="Mobile number with country code (optional)",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 9-15 digits. Format: +919876543210 or 9876543210",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Customer email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Full address", null=True),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the customer",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Active customers can place orders"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="customers_c_name_f018e2_idx"),
                    models.Index(
                        fields=["mobile"], name="customers_c_mobile_e14eb1_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="customers_c_is_acti_91d305_idx"
                    ),
                ],
            },
        ),
    ]
