# Generated by Django 5.2.12 on 2026-03-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="apartment_name",
            field=models.CharField(
                blank=True,
                help_text="Apartment or building name",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="block",
            field=models.CharField(
                blank=True, help_text="Block or tower number", max_length=100, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["apartment_name"], name="customers_c_apartme_92d3b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["block"], name="customers_c_block_23dcf5_idx"),
        ),
    ]
