# Generated by Django 5.2.12 on 2026-03-22 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_product_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offering_date",
                    models.DateField(
                        db_index=True, help_text="Date for this offering", unique=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about this day's offering",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this offering is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily Offering",
                "verbose_name_plural": "Daily Offerings",
                "ordering": ["-offering_date"],
            },
        ),
        migrations.CreateModel(
            name="DailyOfferingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional: Maximum quantity available for this product",
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in the offering"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="offerings.dailyoffering",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Offering Item",
                "verbose_name_plural": "Daily Offering Items",
                "ordering": ["display_order", "id"],
                "unique_together": {("daily_offering", "product")},
            },
        ),
    ]
