# Generated by Django 5.2.12 on 2026-03-28 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSheetConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Friendly name for this integration (e.g., "Mango Pickle Orders")',
                        max_length=100,
                    ),
                ),
                (
                    "sheet_id",
                    models.CharField(
                        help_text="Google Sheet ID (from the URL)", max_length=200
                    ),
                ),
                (
                    "tab_name",
                    models.CharField(
                        default="Form Responses 1",
                        help_text="Name of the tab/worksheet to read from",
                        max_length=100,
                    ),
                ),
                (
                    "field_mapping",
                    models.JSONField(
                        default=dict, help_text="Mapping of our fields to sheet columns"
                    ),
                ),
                (
                    "default_product_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Default product ID if not specified in sheet",
                        null=True,
                    ),
                ),
                (
                    "default_order_type",
                    models.CharField(
                        default="delivery",
                        help_text="Default order type",
                        max_length=20,
                    ),
                ),
                (
                    "last_synced_row",
                    models.IntegerField(
                        default=1,
                        help_text="Last row number that was synced (header is row 1)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "write_back_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Write order number and status back to sheet",
                    ),
                ),
                (
                    "order_number_column",
                    models.CharField(
                        blank=True,
                        help_text='Column to write order number (e.g., "G")',
                        max_length=10,
                    ),
                ),
                (
                    "status_column",
                    models.CharField(
                        blank=True,
                        help_text='Column to write order status (e.g., "H")',
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="google_sheet_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Sheet Configuration",
                "verbose_name_plural": "Google Sheet Configurations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoogleSheetSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rows_processed", models.IntegerField(default=0)),
                ("rows_created", models.IntegerField(default=0)),
                ("rows_skipped", models.IntegerField(default=0)),
                ("rows_failed", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                ("created_order_ids", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="integrations.googlesheetconfig",
                    ),
                ),
                (
                    "synced_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Sheet Sync Log",
                "verbose_name_plural": "Google Sheet Sync Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GoogleSheetOrderRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sheet_row", models.IntegerField(help_text="Row number in the sheet")),
                (
                    "row_hash",
                    models.CharField(
                        help_text="Hash of row data for change detection", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_refs",
                        to="integrations.googlesheetconfig",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_sheet_refs",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Sheet Order Reference",
                "verbose_name_plural": "Google Sheet Order References",
                "unique_together": {("config", "sheet_row")},
            },
        ),
    ]
