# Generated by Django 5.2.12 on 2026-03-21 12:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product name (e.g., Tomato Soup 250ml)",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("soups", "Soups"),
                            ("snacks", "Snacks"),
                            ("sweets", "Sweets"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("pickle", "Pickle"),
                            ("combos", "Combos"),
                            ("other", "Other"),
                        ],
                        help_text="Product category",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Product description", null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit size (e.g., 250ml, 500ml, 1 plate, 1 box)",
                        max_length=50,
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price per unit",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Active products can be offered"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal notes", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="catalog_pro_categor_50f92a_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="catalog_pro_is_acti_14fc6b_idx"
                    ),
                    models.Index(fields=["name"], name="catalog_pro_name_f603c0_idx"),
                ],
                "unique_together": {("name", "unit")},
            },
        ),
        migrations.CreateModel(
            name="ProductCostComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of cost item (e.g., Tomatoes, Chef time, Gas)",
                        max_length=200,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("ingredient", "Ingredient"),
                            ("labor", "Labor"),
                            ("fuel", "Fuel"),
                            ("packaging", "Packaging"),
                            ("transport", "Transport"),
                            ("miscellaneous", "Miscellaneous"),
                        ],
                        help_text="Type of cost component",
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantity used per unit",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        help_text="Unit (e.g., kg, liters, hours, pieces)",
                        max_length=50,
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit of measure",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Auto-calculated: quantity × cost_per_unit",
                        max_digits=10,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this cost belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_components",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Cost Component",
                "verbose_name_plural": "Product Cost Components",
                "ordering": ["item_type", "item_name"],
            },
        ),
    ]
