# Generated by Django 5.2.12 on 2026-03-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Product image URL (defaults to placeholder if not provided)",
                max_length=500,
                null=True,
            ),
        ),
    ]
